#!/bin/sh
# shellcheck disable=SC2068
set -e

# ================================================================================
rm -f perf.data perf.out 2>/dev/null
RUSTFLAGS='-Ctarget-cpu=native -Cforce-frame-pointers=yes' cargo build --profile perf
perf record -g -F 999 --call-graph=dwarf ./target/perf/xfcat $@
# convert report to text data for external viewers
perf script >perf.out
