name: release

on:
  push:
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: write

env:
  # vars for gh cli
  GH_REPO: ${{ github.repository }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_TELEMETRY: 0
  XFCAT_TAG: ${{ github.ref_name }}

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.draft.outputs.version }}
    steps:
      - name: Create Draft Release
        id: draft
        shell: bash
        run: |
          version="${XFCAT_TAG#v}"
          pre=true
          if [[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-.*)? ]]; then
            if [[ -z "${BASH_REMATCH[1]}" ]]; then
           	  pre=false
            fi
          fi
          gh release create "$XFCAT_TAG" --draft --prerelease=$pre --verify-tag --title "Release $version"
          echo "version=$version" >>$GITHUB_OUTPUT

  build:
    name: build-release
    needs: [setup]

    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, target: x86_64-unknown-linux-musl }
          - { os: macos-latest, target: aarch64-apple-darwin }
          - { os: windows-latest, target: x86_64-pc-windows-msvc }

    runs-on: ${{ matrix.os }}
    env:
      XFCAT_VERSION: ${{ needs.setup.outputs.version }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install targets
        run: |
          rustup target add ${{ matrix.target }}

      - name: Build
        run: |
          cargo build --release --verbose --target=${{ matrix.target }}

      - name: Determine Archive name
        shell: bash
        run: |
          os="$(echo "${{ runner.os }}" | perl -ne 'print lc')"
          arch="$(echo "${{ runner.arch }}" | perl -ne 'print lc')"
          echo "ARCHIVE=xfcat-${XFCAT_VERSION}-${os}-${arch}" >>$GITHUB_ENV

      - name: Archive (Windows)
        if: ${{ startsWith(matrix.os, 'windows') }}
        shell: bash
        run: |
          zipfile="${ARCHIVE}.zip"
          sumfile="${ARCHIVE}.zip.sha256"
          # -------------------------------------------------
          7z a "$zipfile" "./target/${{ matrix.target }}/release/xfcat.exe"
          certutil -hashfile "$zipfile" SHA256 >"$sumfile"
          # -------------------------------------------------
          echo "ASSET=$zipfile" >>$GITHUB_ENV
          echo "ASSET_SUM=$sumfile" >>$GITHUB_ENV

      - name: Archive (Unix)
        if: ${{ !startsWith(matrix.os, 'windows') }}
        shell: bash
        run: |
          tarball="${ARCHIVE}.tar.gz"
          sumfile="${ARCHIVE}.tar.gz.sha256"
          # -------------------------------------------------
          strip ./target/release/xfcat
          tar czf "$tarball" -C target/${{ matrix.target }}/release xfcat
          shasum -a 256 "$tarball" >"$sumfile"
          # -------------------------------------------------
          echo "ASSET=$tarball" >>$GITHUB_ENV
          echo "ASSET_SUM=$sumfile" >>$GITHUB_ENV

      - name: Upload Artifacts
        shell: bash
        run: |
          gh release upload "$XFCAT_TAG" "${{ env.ASSET }}" "${{ env.ASSET_SUM }}"

  publish:
    name: publish-release
    needs: [setup, build]
    runs-on: ubuntu-latest
    env:
      XFCAT_VERSION: ${{ needs.setup.outputs.version }}
    steps:
      - name: finalise release
        run: |
          gh release edit "$XFCAT_TAG" --draft=false
